title: Commander Grimoire
description: Where Legends Gather
show_downloads: true
google_analytics:
#theme: jekyll-theme-cayman

# baseurl: "/commander-grimoire-jekyll"
baseurl: ""

permalink: /:categories/:title/

collections:
  posts:
    output: true
    permalink: /articles/:title/
    # permalink: /:title/
  authors:
    output: true
    permalink: /staff/:name/

#remote_theme: pages-themes/cayman@v0.2.0