title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
#theme: jekyll-theme-cayman


collections:
  posts:
    output: true
    permalink: /posts/:title/

#remote_theme: pages-themes/cayman@v0.2.0