title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
#theme: jekyll-theme-cayman

# Default development values
baseurl: ""
url: "http://localhost:4000"

# Production overrides via command line
jekyll_env: development

collections:
  posts:
    output: true
    permalink: /posts/:title/
    # permalink: /:title/

#remote_theme: pages-themes/cayman@v0.2.0